name = "alicesaidhi/conch"
version = "0.3.1"
includes = ["src/**", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
language = { workspace = "alicesaidhi/conch_language" }